### ISSUE TITLE
Add ES module build

### ISSUE THREAD

**Issue by akheron** [raimohanska/lonna#8]
This makes webpack and other bundlers able to tree shake

**Comment by raimohanska** [comment]
Is there any reason to export as CJS at all these days? Should we go all ESM?

**Comment by raimohanska** [comment]
If we want both, what's the sensible way to dual-package in a tree-shakeable way?

**Comment by akheron** [comment]
- 2 tsconfig.jsons to output commonjs modules under dist/cjs and es modules under dist/esm 
- run tsc with both configs in npm run build
- this in package.json: https://github.com/akheron/optics-ts/blob/master/package.json#L17-L19

I think it makes sense to have both commonjs and es modules with Lonna because node cannot handle es modules. Not having commonjs modules in Lonna would make it hard to run harmaja’s unit tests for example.

**Comment by semmel** [comment]
> this in package.json: https://github.com/akheron/optics-ts/blob/master/package.json#L17-L19

@akheron Where did you find that Node.js supports package.json field called "module"? 
```
"module": "./dist/esm/index.js"
``` 
Or is that field included in package.json for some other purpose?

I'd recommend instead to look at [Conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) to specify CJS and ESM bundles.
I.e.
```
"exports": {
    "import": "./main-module.js",
    "require": "./main-require.cjs"
  },
```
Although they might not be supported in Node.js 10 LTS (which will become End-of-life status in April 2021 anyway)

**Comment by raimohanska** [comment]
https://github.com/rollup/rollup/wiki/pkg.module

That’s on the module field

**Comment by semmel** [comment]
> That’s on the module field

Great, its for rollup! Found it's also supported by [@rollup/plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields). 

Note to myself: I do no longer need to use @rollup/importAlias and such to map my bare imports to the ES module files in rollup. 😃  Thanks @raimohanska ! 

So in conclusion [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports) `"exports": { "import: … }` are just required to support `import`ing ES modules from Node.js. Which I do in "isomorphic" (i.e. running insensitive of  Node.js or browser) code.

**Comment by akheron** [comment]
Yeah, also webpack supports the `module` field.

I didn’t know about the conditional exports feature of node, and seems that webpack also supports it starting from v5.

It seems that it could actually be pretty safe to only build es modules as node 14 onwards seems to support them without any hassle. Just set `type: “module”` in `package.json`.

**Comment by akheron** [comment]
... or is the restriction still in place that you cannot import a commonjs module from an es module?
